### ISSUE TITLE
Dockerfile uses the 2019 code

### ISSUE THREAD

**Issue by JBlaschke** [aCampello/coralml#1]
Action Item: Update the `docker` folder to use the new repo. The current version links to a submodule with the 2019 code.

**Comment by JBlaschke** [comment]
Done! @aCampello I had to unpin all the requirements because they where taking waaaaayyyyy to long to build. But as it stands now, we have a GPU-aware image that runs on rap lab 😄

**Comment by aCampello** [comment]
Looks impressive! I will try to run on i.
